## Numpy의 연산과 함수

Python의 Numpy 라이브러리는 기본적인  상수 연산이 가능합니다.

In [3]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)

# 덧셈
add_array = array + 10
print(add_array)

# 뺄셈
sub_array = array - 10
print(sub_array)

# 곱셈
mul_array = array * 10
print(mul_array)

# 나눗셈
div_array = array / 10
print(div_array)

[[12 11]
 [13 12]]
[[-8 -9]
 [-7 -8]]
[[20 10]
 [30 20]]
[[0.2 0.1]
 [0.3 0.2]]


**서로 다른 형태의 Numpy 연산**이 가능합니다.
- Numpy는 서로 다른 형태의 배열을 연산할 때는 행 우선으로 수행됩니다.
- 행이 동일할 경우에는 열을 동적으로 변환하여 연산이 수행됩니다.
- **브로드캐스트**: 형태가 다른 배열을 연산할 수 있도록 배열의 형태를 동적으로 변환

In [4]:
import numpy as np

array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)
array3 = array1 + array2

print(array3)

[[0 2]
 [2 4]]


Numpy는 **마스킹 연산**이 가능합니다.

In [7]:
import numpy

# Numpy 원소의 값을 조건에 따라 바꿀 때는 다음과 같이 합니다.
# 대체로 이미지 처리(Image Processing)에서 자주 활용됩니다.

array1 = np.arange(16).reshape(4, 4)
print(array1)

array2 = array1 < 10
print(array2)

array1[array2] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


Numpy는 **다양한 집계 함수**가 존재합니다.

In [8]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


Numpy 원소들은 특정한 기준에 따라서 **정렬**할 수 있습니다.

In [13]:
import numpy as np

# Numpy 원소 오름차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

# Numpy 원소 내림차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1])

# 각 행을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
array.sort(axis=0)
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


Numpy 관련 자주 사용되는 함수는 다음과 같습니다.

In [14]:
import numpy as np

# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print(array)

# 난수의 재연(실행마다 결과 동일)
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))

# Numpy 배열 객체 복사
array1 = np.arange(0, 10)
array2 = array1.copy()
print(array2)

# 중복된 원소 제거
array = np.array([1, 1, 2, 3, 3, 3, 1])
print(np.unique(array))

[ 0.   2.5  5.   7.5 10. ]
[[4 9 6]
 [3 3 7]]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
